/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogCollectionRouteImport } from './routes/catalog.$collection'
import { Route as ExperimentSlugRouteImport } from './routes/experiment.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogCollectionRoute = CatalogCollectionRouteImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => CatalogRoute,
} as any)
const ExperimentSlugRoute = ExperimentSlugRouteImport.update({
  id: '/experiment/$slug',
  path: '/experiment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/catalog/$collection': typeof CatalogCollectionRoute
  '/experiment/$slug': typeof ExperimentSlugRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog/$collection': typeof CatalogCollectionRoute
  '/experiment/$slug': typeof ExperimentSlugRoute
  '/catalog': typeof CatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/catalog/$collection': typeof CatalogCollectionRoute
  '/experiment/$slug': typeof ExperimentSlugRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/catalog/$collection'
    | '/experiment/$slug'
    | '/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalog/$collection' | '/experiment/$slug' | '/catalog'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/catalog/$collection'
    | '/experiment/$slug'
    | '/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  ExperimentSlugRoute: typeof ExperimentSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/$collection': {
      id: '/catalog/$collection'
      path: '/$collection'
      fullPath: '/catalog/$collection'
      preLoaderRoute: typeof CatalogCollectionRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/experiment/$slug': {
      id: '/experiment/$slug'
      path: '/experiment/$slug'
      fullPath: '/experiment/$slug'
      preLoaderRoute: typeof ExperimentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CatalogRouteChildren {
  CatalogCollectionRoute: typeof CatalogCollectionRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogCollectionRoute: CatalogCollectionRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRouteWithChildren,
  ExperimentSlugRoute: ExperimentSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
